services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: [ 'console.command' ]
    
    VendorMachine\:
        resource: '../../src/*'
        exclude: '../../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    VendorMachine\App\:
        resource: '../*'
        exclude: '../{DependencyInjection,Entity,Tests,Kernel.php}'

    VendorMachine\App\Application:
        public: true
        arguments:
          - !tagged_iterator console.command

    VendorMachine\Machine\Domain\MachineBalanceRepository: '@VendorMachine\Machine\Infrastructure\YamlMachineBalanceRepository'
    VendorMachine\Machine\Domain\MachineRepository: '@VendorMachine\Machine\Infrastructure\YamlMachineProductsRepository'