#!/bin/bash

docker run -d -t                            \
    --name vendor-machine                   \
    --network vendor-machine_net            \
    -v "$PWD":/usr/src                      \
    -w /usr/src                             \
    vendor-machine.php-cli
