#!/bin/bash

docker run -it --rm                                 \
    --name vendor-machine-script                        \
    --network vendor-machine_net                    \
    -v "$PWD":/usr/src                              \
    -e XDEBUG_MODE=coverage                         \
    -w /usr/src                                     \
    vendor-machine.php-cli php vendor/bin/phpunit $@
