services:
    _defaults:
        autowire: true
        autoconfigure: true

    # VendorMachine\Tests\:
    #     resource: '../tests/machine/*'

    VendorMachine\App\Tests\:
        resource: '../tests/app/*'